### ISSUE TITLE
(v0.15.0) Randomizer is stuffing massive amounts of enemies in single rooms.

### ISSUE THREAD

**Issue by minnowz** [brgmnn/autogen-rundown#11]
I did 3 separate levels on 2 separate seeds. first the test level on one seed, the other a A1 and a B2 level on a second seed. the randomizer seems to currently greatly prefer stuffing a huge amount of enemies (around 20-30 enemies) in a single room rather then distributing that number across the entire zone. this has lead to me dealing with one absolute clown car of a room and then the rest of the zone being empty.   
![image](https://github.com/brgmnn/autogen-rundown/assets/50928659/a76531c6-1918-49d8-9cff-7cac06d8cc6f)
![image](https://github.com/brgmnn/autogen-rundown/assets/50928659/beb3e1e4-ba9b-41b8-874a-6b3eb9b061d1)
![image](https://github.com/brgmnn/autogen-rundown/assets/50928659/fddb0be7-02a1-4fc6-8327-39936ca2ebd4)

It does not seem to happen 100% of the time, but in those cases it's almost always like ~4 enemies spawning in a small room. (do rooms have enemy caps?)

**Comment by minnowz** [comment]
as of 0.16.0, the randomizer still seems to like stuff at least most of a zone's enemies into one room

**Comment by brgmnn** [comment]
Thanks for the ticket submission, enemy balancing is still something that needs a lot of work. I'll check in to this, do you have a specific seed/level/zone you think has too many enemies? I see from your screenshots you're on seed `12_42_3131` and on A1/B1.

> It does not seem to happen 100% of the time, but in those cases it's almost always like ~4 enemies spawning in a small room. (do rooms have enemy caps?)

I can't specify exact enemies per room, only enemy groups to be spawned per zone. So larger zones with a lot of rooms there may be an issue if enemy groups are too lumpy.

**Comment by minnowz** [comment]
it's something I keep notice keep happening regardless of level or seed in my experience, to the point where once I know which room has the enemies in the zone, I am somewhat surprised if there is any enemies in any of the other rooms. I think (not sure) the last version I played before version 0.15.0 was either version 0.12.0 or 0.13.0 and I don't remember noticing this issue during then.
