### ISSUE TITLE
V0.24.0 Completely nonfuctional 

### ISSUE THREAD

**Issue by minnowz** [brgmnn/autogen-rundown#13]
Attempted to try out the newest version, could not get it to load and Rundown 7 was always it's vanilla form. Down patching to V0.23.2 immediately solved the issue.

**Comment by brgmnn** [comment]
Can you check if this is still the case in 0.31.0?

**Comment by minnowz** [comment]
this is no longer the case, I'm pretty sure 0.24.2 fixed this issue
